// This code was autogenerated with `dbus-codegen-rust -d org.gnome.ScreenSaver -p /org/gnome/ScreenSaver -m None`, see https://github.com/diwic/dbus-rs
use dbus as dbus;
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopDBusProperties {
    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<::std::collections::HashMap<String, arg::Variant<Box<dyn arg::RefArg + 'static>>>, dbus::Error>;
    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error>;
}

impl<'a, C: ::std::ops::Deref<Target=blocking::Connection>> OrgFreedesktopDBusProperties for blocking::Proxy<'a, C> {

    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Get", (interface_name, property_name, ))
            .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>, )| Ok(r.0, ))
    }

    fn get_all(&self, interface_name: &str) -> Result<::std::collections::HashMap<String, arg::Variant<Box<dyn arg::RefArg + 'static>>>, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "GetAll", (interface_name, ))
            .and_then(|r: (::std::collections::HashMap<String, arg::Variant<Box<dyn arg::RefArg + 'static>>>, )| Ok(r.0, ))
    }

    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Set", (interface_name, property_name, value, ))
    }
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: ::std::collections::HashMap<String, arg::Variant<Box<dyn arg::RefArg + 'static>>>,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

impl<'a, C: ::std::ops::Deref<Target=blocking::Connection>> OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C> {

    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> Result<(), dbus::Error>;
    fn get_machine_id(&self) -> Result<String, dbus::Error>;
}

impl<'a, C: ::std::ops::Deref<Target=blocking::Connection>> OrgFreedesktopDBusPeer for blocking::Proxy<'a, C> {

    fn ping(&self) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgGnomeScreenSaver {
    fn lock(&self) -> Result<(), dbus::Error>;
    fn get_active(&self) -> Result<bool, dbus::Error>;
    fn set_active(&self, value: bool) -> Result<(), dbus::Error>;
    fn get_active_time(&self) -> Result<u32, dbus::Error>;
}

impl<'a, C: ::std::ops::Deref<Target=blocking::Connection>> OrgGnomeScreenSaver for blocking::Proxy<'a, C> {

    fn lock(&self) -> Result<(), dbus::Error> {
        self.method_call("org.gnome.ScreenSaver", "Lock", ())
    }

    fn get_active(&self) -> Result<bool, dbus::Error> {
        self.method_call("org.gnome.ScreenSaver", "GetActive", ())
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn set_active(&self, value: bool) -> Result<(), dbus::Error> {
        self.method_call("org.gnome.ScreenSaver", "SetActive", (value, ))
    }

    fn get_active_time(&self) -> Result<u32, dbus::Error> {
        self.method_call("org.gnome.ScreenSaver", "GetActiveTime", ())
            .and_then(|r: (u32, )| Ok(r.0, ))
    }
}

#[derive(Debug)]
pub struct OrgGnomeScreenSaverActiveChanged {
    pub new_value: bool,
}

impl arg::AppendAll for OrgGnomeScreenSaverActiveChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.new_value, i);
    }
}

impl arg::ReadAll for OrgGnomeScreenSaverActiveChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgGnomeScreenSaverActiveChanged {
            new_value: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgGnomeScreenSaverActiveChanged {
    const NAME: &'static str = "ActiveChanged";
    const INTERFACE: &'static str = "org.gnome.ScreenSaver";
}

#[derive(Debug)]
pub struct OrgGnomeScreenSaverWakeUpScreen {
}

impl arg::AppendAll for OrgGnomeScreenSaverWakeUpScreen {
    fn append(&self, _: &mut arg::IterAppend) {
    }
}

impl arg::ReadAll for OrgGnomeScreenSaverWakeUpScreen {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgGnomeScreenSaverWakeUpScreen {
        })
    }
}

impl dbus::message::SignalArgs for OrgGnomeScreenSaverWakeUpScreen {
    const NAME: &'static str = "WakeUpScreen";
    const INTERFACE: &'static str = "org.gnome.ScreenSaver";
}
